### ISSUE TITLE
RuntimeError: The quantizer passed does not adhere to the quantization protocol.

### ISSUE THREAD

**Issue by nachiket** [Xilinx/logicnets#47]
I am trying to simple jsc-s training example and getting the following error. I am running in a manually installed mode.

python3 train.py --arch jsc-s --log-dir ./jsc-s
/zfsspare/nachiket/logicnets/examples/jet_substructure/dataset.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(f)
/zfsspare/nachiket/logicnets/examples/jet_substructure/dataset.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(f)
/zfsspare/nachiket/logicnets/examples/jet_substructure/dataset.py:39: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.config = yaml.load(f)
Traceback (most recent call last):
  File "train.py", line 317, in <module>
    model = JetSubstructureNeqModel(model_cfg)
  File "/zfsspare/nachiket/logicnets/examples/jet_substructure/models.py", line 46, in __init__
    input_quant = QuantBrevitasActivation(QuantHardTanh(model_config["input_bitwidth"], max_val=1., narrow_range=False, quant_type=QuantType.INT, scaling_impl_type=ScalingImplType.PARAMETER), pre_transforms=[bn_in, input_bias])
  File "/home/nachiket/.local/lib/python3.8/site-packages/brevitas/nn/quant_activation.py", line 96, in __init__
    QuantNLAL.__init__(
  File "/home/nachiket/.local/lib/python3.8/site-packages/brevitas/nn/quant_layer.py", line 36, in __init__
    QuantNonLinearActMixin.__init__(self, act_impl, passthrough_act, act_quant, **kwargs)
  File "/home/nachiket/.local/lib/python3.8/site-packages/brevitas/nn/mixin/act.py", line 118, in __init__
    QuantProxyMixin.__init__(
  File "/home/nachiket/.local/lib/python3.8/site-packages/brevitas/nn/mixin/base.py", line 73, in __init__
    raise RuntimeError(
RuntimeError: The quantizer passed does not adhere to the quantization protocol.

**Comment by nachiket** [comment]
Never mind found https://github.com/Xilinx/logicnets/issues/40#issue-1852775046
